[package]
name = "fia-docs-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sign-v4 = { git = "https://github.com/MarkusTheOrt/aws-sign-v4", version = "0.2.0" }
axum = { version = "0.7.4" }
axum-macros = "0.4.1"
chrono = { version = "0.4.26", features = ["serde"] }
dotenvy = "0.15.7"
html5ever = "0.26.0"
rayon = "1.7.0"
reqwest = "0.11.18"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
sha256 = "1.1.4"
sqlx = { version = "0.7.3", features = ["chrono", "json", "mysql", "runtime-tokio-rustls"] }
tokio = { version = "1.28.2", features = ["full"] }
tower-layer = "0.3.2"
tower-service = "0.3.2"
urlencoding = "2.1.2"
